In [138]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy
from scipy.stats import skew,kurtosis
import seaborn as sns
from scipy.stats import norm

In [139]:
def get_data(symbol):
    df = pd.read_csv("{}".format(symbol),index_col="Date",parse_dates=True)
    return df['Close']

def port_ret(weights,returns):
    return np.sum(returns.mean()*weights)*252

def port_vol(weights,returns):
    return np.sqrt(np.dot(weights.T,np.dot(returns.cov()*252,weights)))



for symbol in ['AAPL.csv','JNJ.csv','XOM.csv']:
    if symbol == 'AAPL.csv':
        d1 = get_data(symbol)
    elif symbol == 'JNJ.csv':
        d2 = get_data(symbol)
    elif symbol == 'XOM.csv':
        d3 = get_data(symbol)
    

dict = {'AAPL':d1,
        'JNJ':d2,
        'XOM':d3}
df0 = pd.DataFrame(dict)
df0['AAPL'] = pd.to_numeric(df0['AAPL'])
df0['JNJ'] = pd.to_numeric(df0['JNJ'])
df0['XOM'] = pd.to_numeric(df0['XOM'])

df0

AAPL         JNJ         XOM
Date                                          
2021-04-23  134.320007  165.520004   55.570000
2021-04-26  134.720001  164.119995   55.680000
2021-04-27  134.389999  163.179993   56.410000
2021-04-28  133.580002  161.979996   58.110001
2021-04-29  133.479996  164.199997   58.939999
...                ...         ...         ...
2023-04-17  165.229996  165.669998  114.699997
2023-04-18  166.470001  161.009995  116.940002
2023-04-19  167.630005  162.529999  116.570000
2023-04-20  166.649994  163.580002  115.639999
2023-04-21  165.020004  162.690002  116.010002

[503 rows x 3 columns]

In [140]:
port_df = np.log(df0/df0.shift(1))
port_df.dropna()


    

AAPL       JNJ       XOM
Date                                    
2021-04-26  0.002973 -0.008494  0.001978
2021-04-27 -0.002453 -0.005744  0.013025
2021-04-28 -0.006045 -0.007381  0.029691
2021-04-29 -0.000749  0.013612  0.014182
2021-04-30 -0.015249 -0.008993 -0.029267
...              ...       ...       ...
2023-04-17  0.000121 -0.001026 -0.011701
2023-04-18  0.007477 -0.028531  0.019341
2023-04-19  0.006944  0.009396 -0.003169
2023-04-20 -0.005863  0.006440 -0.008010
2023-04-21 -0.009829 -0.005456  0.003195

[502 rows x 3 columns]

In [141]:
avg_returns = port_df.mean()*252



   

In [142]:
volatility = port_df.std()

    

In [143]:
cov = port_df.cov()*252


    


In [144]:
corr = port_df.corr()

    

In [145]:
skew(port_df.dropna())

array([ 0.04147871,  0.17785273, -0.23083738])

In [146]:
skewness = pd.DataFrame(skew(port_df.dropna()),index=['AAPL','JNJ','XOM'])

    


In [147]:
kurt=pd.DataFrame(kurtosis(port_df.dropna()),index=['AAPL','JNJ','XOM'])



In [148]:
with pd.ExcelWriter("WQU.xlsx") as writer:
    port_df.to_excel(writer,sheet_name="Sheet 1")
    avg_returns.to_excel(writer,sheet_name="Sheet 2")
    volatility.to_excel(writer,sheet_name="Sheet 3")
    cov.to_excel(writer,sheet_name="Sheet 4")
    corr.to_excel(writer,sheet_name="Sheet 5")
    skewness.to_excel(writer,sheet_name="Sheet 6")
    kurt.to_excel(writer,sheet_name="Sheet 7")

In [149]:
weights=np.random.random(3)
weights /= np.sum(weights)
weights

array([0.16775797, 0.32066128, 0.51158075])

In [150]:
prets = []
pvol = []

for p in range(503):
    alloc = np.random.random(3)
    alloc /= np.sum(alloc)
    prets.append(port_ret(alloc,port_df))
    pvol.append(port_vol(alloc,port_df))
prets = np.array(prets)
pvol = np.array(pvol)

prets



array([ 0.15302786,  0.12111024,  0.27532836,  0.06661669,  0.08976503,
        0.05323828,  0.1714881 ,  0.05406869,  0.16219139,  0.18678271,
        0.17853744,  0.16545503,  0.16788664,  0.19153344,  0.11558911,
        0.18001847,  0.07522943,  0.16145398,  0.22267596,  0.15481564,
        0.19736001,  0.17046879,  0.21557229,  0.05182814,  0.12525297,
        0.09097113,  0.22437411,  0.10843536,  0.18879854,  0.22313036,
        0.23467057,  0.21523347,  0.14849954,  0.04280713,  0.12712713,
        0.08160621,  0.13565137,  0.10884361,  0.17090993,  0.2868319 ,
        0.12579888,  0.06869945,  0.06186483,  0.00726022,  0.20304846,
        0.16267943,  0.15130915,  0.07740707,  0.12585287,  0.1859586 ,
        0.09961203,  0.10863374,  0.14633414,  0.17033102,  0.12559672,
        0.15712009,  0.24894844,  0.15958258,  0.1364762 ,  0.0998958 ,
        0.10458883,  0.20505996,  0.10854509,  0.16845075,  0.18256007,
        0.11273588,  0.19671998,  0.24543136,  0.17455555,  0.17

In [151]:
port_df['Portfolio Returns']=prets.tolist()

port_df['Portfolio Volatility']=pvol.tolist()


port_df


AAPL       JNJ       XOM  Portfolio Returns  \
Date                                                          
2021-04-23       NaN       NaN       NaN           0.153028   
2021-04-26  0.002973 -0.008494  0.001978           0.121110   
2021-04-27 -0.002453 -0.005744  0.013025           0.275328   
2021-04-28 -0.006045 -0.007381  0.029691           0.066617   
2021-04-29 -0.000749  0.013612  0.014182           0.089765   
...              ...       ...       ...                ...   
2023-04-17  0.000121 -0.001026 -0.011701           0.168674   
2023-04-18  0.007477 -0.028531  0.019341           0.143339   
2023-04-19  0.006944  0.009396 -0.003169           0.138743   
2023-04-20 -0.005863  0.006440 -0.008010           0.102145   
2023-04-21 -0.009829 -0.005456  0.003195           0.151495   

            Portfolio Volatility  
Date                              
2021-04-23              0.171787  
2021-04-26              0.219418  
2021-04-27              0.244430  
2021-04-28              0.186363  
2021-04-29              0.211771  
...                          ...  
2023-04-17              0.190334  
2023-04-18              0.194061  
2023-04-19              0.165281  
2023-04-20              0.187694  
2023-04-21              0.180382  

[503 rows x 5 columns]

In [152]:
port_df['Portfolio Returns'].mean()

0.15741692725210876

In [153]:
port_df['Portfolio Returns'].std()

0.05933437108625893

In [154]:
cov = port_df.cov()*252

In [155]:
corr=port_df.corr()

In [156]:
skew(port_df['Portfolio Returns'].dropna())

0.08774884712026274

In [157]:
kurtosis(port_df['Portfolio Returns'].dropna())

-0.034953581344269846

In [158]:
with pd.ExcelWriter("New Microsoft Excel Worksheet.xlsx") as writer:
    port_df.to_excel(writer,sheet_name="Sheet 1")
    cov.to_excel(writer,sheet_name="Sheet 4")
    corr.to_excel(writer,sheet_name="Sheet 5")